Implement zet commit and fix local_dir

diff --git a/bin/zet b/bin/zet
--- a/bin/zet
+++ b/bin/zet
@@ -59,7 +59,7 @@ elif (( $#arg_edit )); then
 
 else
 	# New zet
-	local dir="$zer_dir/$(date +'%m%d%Y%I%M%S')"
+	local dir="$zet_dir/$(date +'%m%d%Y%I%M%S')"
 	if [[ -d $dir ]]; then
 		echo 'zet already exists'
 		exit 1
@@ -75,9 +75,14 @@ else
 	fi
 	${EDITOR:-vi} "$dir/README.md"
 
-	if read -q 'choice?Commit?'; then
-		cd "$zet_dir"
-		# TODO get commit title from first line of the zet (after the #)
-		# TODO commit the zet
+	if read -q 'choice?Commit? '; then
+		if [[ -n $(git diff --name-only --cached) ]]; then
+			echo 'cannot commit, there are already staged files'
+			exit 1
+		fi
+		commit_title=$(cat "$dir/README.md" | head -1 | sed 's/\# //')
+		git add "$dir"
+		git commit -m "$commit_title"
+		git push
 	fi
 fi
