Handle environments with no node cleanly
by disabling coc.nvim. This prevents an error message on vim startup in
such environments.

diff --git a/vim/install b/vim/install
--- a/vim/install
+++ b/vim/install
@@ -12,19 +12,25 @@ if ! command -v node >/dev/null 2>&1; then
     fi
     eval $package_manager node
   else
-    sudo apt install -y npm
-    sudo npm install -y -g npm
+    # Try installing, but allow it to fail without aborting the whole script
+    sudo apt install -y npm || echo "  Failed to install npm via apt"
+    sudo npm install -y -g npm || echo "  Failed to upgrade npm"
   fi
 fi
-echo '  installing CoC extensions'
-if [ "$DOT_TYPE" == "full" ]; then
-  coc_extensions='coc-json coc-html coc-go coc-jedi coc-java'
+
+if command -v node >/dev/null 2>&1; then
+  echo '  installing CoC extensions'
+  if [ "$DOT_TYPE" == "full" ]; then
+    coc_extensions='coc-json coc-html coc-go coc-jedi coc-java'
+  else
+    coc_extensions='coc-json coc-html'
+  fi
+  echo "WARNING +CocInstall is not working from shell, I get an error 'E605: Exception not caught: Error on \"installExtensions\" request: ...'. Run it manually instead."
+  # vim -esN +"CocInstall -sync $coc_extensions | q" +qall
+  vim -N +CocUpdateSync +qall
 else
-  coc_extensions='coc-json coc-html'
+  echo '  Node not found, skipping CoC extension installation'
 fi
-echo "WARNING +CocInstall is not working from shell, I get an error 'E605: Exception not caught: Error on "installExtensions" request: ...'. Run it manually instead."
-# vim -esN +"CocInstall -sync $coc_extensions | q" +qall
-vim -N +CocUpdateSync +qall
 echo '  installing helptags'
 for plugin in $(find -H "$HOME/.vim/pack/plugin/start/" -maxdepth 2 -name 'doc'); do
   vim -esN +"helptags $plugin" +qall
